export const CREATE_FORM_DATA = 'CREATE_FORM_DATA'
export const CREATE_FORM_DATA_SUCCESS = 'CREATE_FORM_DATA_SUCCESS'
export const CREATE_FORM_DATA_FAIL = 'CREATE_FORM_DATA_FAIL'

export const GET_FORM_DATA = 'GET_FORM_DATA'
export const GET_FORM_DATA_SUCCESS = 'GET_FORM_DATA_SUCCESS'
export const GET_FORM_DATA_FAIL = 'GET_FORM_DATA_FAIL'

export const GET_SINGLE_FORM_DATA = 'GET_SINGLE_FORM_DATA'
export const GET_SINGLE_FORM_DATA_SUCCESS = 'GET_SINGLE_FORM_DATA_SUCCESS'
export const GET_SINGLE_FORM_DATA_FAIL = 'GET_SINGLE_FORM_DATA_FAIL'

export const DELETE_FORM_DATA = 'DELETE_FORM_DATA'
export const DELETE_FORM_DATA_SUCCESS = 'DELETE_FORM_DATA_SUCCESS'
export const DELETE_FORM_DATA_FAIL = 'DELETE_FORM_DATA_FAIL'

export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA'
export const UPDATE_FORM_DATA_SUCCESS = 'UPDATE_FORM_DATA_SUCCESS'
export const UPDATE_FORM_DATA_FAIL = 'UPDATE_FORM_DATA_FAIL'
