export const CREATE_ACCOUNT_DATA = 'CREATE_ACCOUNT_DATA'
export const CREATE_ACCOUNT_DATA_SUCCESS = 'CREATE_ACCOUNT_DATA_SUCCESS'
export const CREATE_ACCOUNT_DATA_FAIL = 'CREATE_ACCOUNT_DATA_FAIL'

export const CREATE_PERSONAL_DATA = 'CREATE_PERSONAL_DATA'
export const CREATE_PERSONAL_DATA_SUCCESS = 'CREATE_PERSONAL_DATA_SUCCESS'
export const CREATE_PERSONAL_DATA_FAIL = 'CREATE_PERSONAL_DATA_FAIL'

export const CREATE_PREFERENCES_DATA = 'CREATE_PREFERENCES_DATA'
export const CREATE_PREFERENCES_DATA_SUCCESS = 'CREATE_PREFERENCES_DATA_SUCCESS'
export const CREATE_PREFERENCES_DATA_FAIL = 'CREATE_PREFERENCES_DATA_FAIL'

export const GET_ACCOUNT_DATA = 'GET_ACCOUNT_DATA'
export const GET_ACCOUNT_DATA_SUCCESS = 'GET_ACCOUNT_DATA_SUCCESS'
export const GET_ACCOUNT_DATA_FAIL = 'GET_ACCOUNT_DATA_FAIL'

export const GET_PERSONAL_DATA = 'GET_PERSONAL_DATA'
export const GET_PERSONAL_DATA_SUCCESS = 'GET_PERSONAL_DATA_SUCCESS'
export const GET_PERSONAL_DATA_FAIL = 'GET_PERSONAL_DATA_FAIL'

export const GET_PREFERENCES_DATA = 'GET_PREFERENCES_DATA'
export const GET_PREFERENCES_DATA_SUCCESS = 'GET_PREFERENCES_DATA_SUCCESS'
export const GET_PREFERENCES_DATA_FAIL = 'GET_PREFERENCES_DATA_FAIL'
